[패널티킥] Hugh-KR 미션 제출합니다.
miseongk/kirikiri-penalty-kick pull request #10
Opened 2023-10-05 12:55 UTC by Hugh-KR

### ✏️ PR 타입
- [X] 미션 제출

### ☄️ 반영 브랜치
- Hugh-KR / main -> miseongk / Hugh-KR

### 👨‍💻 진행하며 학습하고 지키려 노력 했던 원칙
- **자바 코드 컨벤션**
  - checkstyle을 사용해 지속적으로 확인
  - LF 사용

- **커밋 메시지 컨벤션**

- **PR 컨벤션**

- **기능 단위 커밋**
  - 어디까지가 하나의 기능인지 지속적으로 생각 

- **MVC모델 학습 및 적용**
  - Controller: 사용자의 요청을 받고, 프로그램 실행
  - Domain: 기능 구현에 필요한 요소들
  - Service: 비즈니스 로직
  - View: 인풋, 아웃풋으로 사용자와 UI의 상호작용

- **SRP(단일 책임 원칙)**
  - 클래스 별로 기능을 나눠, 변경이 생겼을 때 파급효과를 줄임

- **객체지향 생활체조 원칙을 지킨 클린코드**
  -  indent가 최대한 1을 벗어나지 않도록 구현
  - else.switch를 사용하지 않음
  - stream 활용법
  - ByteArrayOutputStream을 사용한 테스트 코드 작성
  - 모든 원시 값과 문자열 포장 (하드코딩 X)
  - 최대한 하나의 메서드는 하나의 기능
  - 메서드명, 변수명을 축약없이 작성하여 직관성 높임
  - 디미터 법칙 적용
  - 최대한 하나의 클래스가 50줄을 넘지 않도록 설계
  - 주석 사용하지 않음
  - 최대한 꼼꼼한 단위 테스트
  - 3개 이상의 인스턴스 변수 X
  - getter/setter 객체 상태 가져오는 꼭 필요한 부분에만 사용

### 📖 테스트 결과
- main, domain, view 분리하여 테스트 진행

2023-10-05 14:28 UTC, scarlet0o0 commented on src/main/java/penaltykick/domain/ComputerPosition.java
> +	private static final int END_RANGE = 3;
안녕하세요 Hugh-KR 제 코드에 리뷰 달아주셔서 감사합니다. Hugh-KR님은 저보다 더 객체지향적으로 코드 짜신거 같아 부럽네요.. 그런데 궁금한점이 있어 질문드려요! `POSITION_LENGTH`, `START_RANGE`, `END_RANGE` 상수들은 `PlayerPosition` 클래스에도 선언되어 있던데 enum으로 합치지 않고 두번 사용하신 이유가 있나요?

2023-10-05 14:32 UTC, younghoondoodoom requested changes
안녕하세요 Hugh님~! 다른 분들꺼 리뷰하려다가 커밋 수와 file change수를 보고 깜짝 놀라서 리뷰하게되었습니다..! 그럼 잘 부탁드립니다!

java를 몇번 사용해보신 경험이 있는것 같아요! 객체 분리, 책임 분리에 대해서 생각하고 짜시는게 티가 납니다!
다만, 단순히 객체를 나누는 것을 넘어서, 해당 객체를 처음 사용하는 사람이 편하기 좋게 만들면 좋을 것 같아요! 즉, 유지보수성이라고 봐야겠죠? 어떤 객체를 만드는 사람은 당연히 그 객체의 사용법을 잘 알고있습니다. 하지만 새로 그 객체를 사용하는 사람은 document를 만들어놓지 않는이상 사용하기 힘들 수 있습니다! 
이 부분 생각하시면서 리펙토링 진행해보시면 좋을 것 같아요!

고생하셨습니다🙇‍♂️

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/controller/SoccerGameController.java
> +		List<Integer> computerPosition = new ComputerPosition().getComputerPosition();
view, service, controller, domain를 만드셨네요!
A객체에서 B객체를 호출하게 되면 A는 B에 의존한다고 합니다. B객체가 뭔가 변화했을때, A객체도 바뀌어야할 여지가 있으니까요.
그렇다면 여기서 Controller가 domain 객체에 의존하고 있습니다. service도 domain객체에 의존하고 있고요.
그렇다면 domain이 바뀌었을때 Controller, Service 모두 바뀔 수도 있을 것 같아요.

Hugh님이 생각하시는 service의 역할은 무엇인가요?

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/controller/SoccerGameController.java
> +}
두 메소드가 완전히 동일한데 두개로 나눌 필요가 있을까요?

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/controller/SoccerGameController.java
> +		this.soccerGameService = new SoccerGameService();
service를 직접 생성하면 어떤 장점이 있을까요?

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/domain/ComputerPosition.java
> +	private final Random random = new Random();
Random 값을 정확하게 테스트하기에는 힘들겠네요! 테스트 하기 힘든 구조는 한 번 더 추상화 해야할 포인트라고 생각합니다!

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/domain/SoccerGame.java
> +	public void inputPlayerPosision(String str) {
🥲

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/service/SoccerGameService.java
> +		return soccerGame.getGameResult();
해당 service에서 똑같은 `soccerGame` 객체하고 일방적으로 요청만 보내고 있네요! 요청, 응답을 하면서 `soccerGame`가 메세지를 주고받도록 수정해보세요!

힌트는 소통하는 두 객체는 서로 메세지를 주고받는다가 핵심입니다!

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/domain/SoccerGame.java
> +	public void playerCountScore() {
playerPosition가 초기화되기 전에 이 메소드가 호출되면 문제가 될 것 같아요! 이러한 이유로 객체는 서로 메세지를 주고받아야한답니다

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/domain/SoccerGame.java
> +	public GameResult getGameResult() {
이 메소드도 위랑 같은 의견이에요~! gameResult가 초기화 되기 전에 이 메소드가 호출되면 문제가 될 수 있습니다!

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/domain/GameResult.java
> +	private static final String GOAL_FAIL = "X";
이 부분은 사용자한테 보여지는 부분입니다! 만약 "O", "X"가 "성공", "실패"로 바뀐다면 해당 도메인 클래스가 직접 바뀌어야겠죠? 다르게 표현할 수 있는 방식은 없을까요? 예를 boolean list를 활용할 수도 있을 것 같아요!

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/domain/GameResult.java
> +	private int countGoal(List<Integer> computerPos, List<Integer> playerPos) {
해당 메소드 파라미터들은 사용하지 않고있습니다..!

2023-10-05 14:32 UTC, younghoondoodoom commented on src/main/java/penaltykick/view/InputView.java
View 객체들 분리한거 너무 좋네요~!

2023-10-05 14:32 UTC, younghoondoodoom commented on src/test/java/penaltykick/domain/GameResultTest.java
테스트도 짜시는군요!! 👍👍

2023-10-05 14:32 UTC, younghoondoodoom commented on src/test/java/penaltykick/domain/GameResultTest.java
> +import penaltykick.view.OutputView;
intellij 자동 정렬 기능을 검색하고 사용해보세요!

2023-10-05 14:52 UTC, Hugh-KR commented on src/main/java/penaltykick/domain/ComputerPosition.java
> +	private static final int END_RANGE = 3;
안녕하세요 scarlet0o0님 좋은 질문 감사드립니다. 말씀하신 부분은 '캡슐화'를 신경쓰며 구현한 부분이에요.
`enum`으로 합치면 코드 수도 줄고 한번에 관리하기도 편하다고 생각하지만 `getter / setter`를 사용하며 자칫 정보가 노출될까 우려되어 두번 사용했습니다! (솔직히 자신은 없어요 😂)

2023-10-06 05:26 UTC, Hugh-KR commented on src/main/java/penaltykick/controller/SoccerGameController.java
> +		List<Integer> computerPosition = new ComputerPosition().getComputerPosition();
안녕하세요 구체적인 피드백 남겨주셔서 정말 감사합니다. 답변 하나하나 소중히 읽으면서 다시 한번 공부해 봤어요.

우선 제가 생각하는 service의 역할은 `Controller로부터 넘어온 데이터를 가공해서 다시 Controller로 넘기는 것` 입니다. 그리고 요구사항이 변경되었을 때 코드를 수정하는 것이 아닌 다른 domain 로직을 생성해서 갈아 끼우는 방식으로 사용하고 싶었어요(OCP)

Controller의 경우 domain, view에 의존할 수 있다고 인지하고 있었는데 혹시 의존을 줄일 수 있는 좋은 방법이 있을까요?

2023-10-06 06:08 UTC, Hugh-KR commented on src/main/java/penaltykick/controller/SoccerGameController.java
> +		this.soccerGameService = new SoccerGameService();
main에서 생성해서 가지고 오는 방식도 고려해봤는데 기능 확장을 고려했을 때 의존관계가 복잡해질 수 도 있다고 생각했습니다!
혹시 안티 패턴 일까요..?

2023-10-06 06:11 UTC, Hugh-KR commented on src/main/java/penaltykick/domain/GameResult.java
> +	private int countGoal(List<Integer> computerPos, List<Integer> playerPos) {
그러네요 😂 바로 수정했어요 감사합니다

2023-10-06 06:11 UTC, Hugh-KR commented on src/main/java/penaltykick/view/InputView.java
감사합니다 ㅠㅠㅠ

2023-10-06 06:52 UTC, Hugh-KR commented on src/main/java/penaltykick/domain/GameResult.java
> +	private static final String GOAL_FAIL = "X";
domain 로직을 보호해야 한다고 말씀해 주시는 거죠? OutputView에서 처리하는 방향으로 리팩토링해 보겠습니다!!

2023-10-06 07:04 UTC, Hugh-KR commented on src/main/java/penaltykick/domain/SoccerGame.java
> +	public void playerCountScore() {
맞습니다. 짜면서도 고민된 부분인데 해결법이 떠오르지않아 그냥 구현해버렸거든요 😂
좀 더 찾아보고 고민해 보겠습니다!

2023-10-07 08:16 UTC, merged