[패널티킥] 이진기 미션 제출합니다.
miseongk/kirikiri-penalty-kick pull request #4
Opened 2023-10-04 09:05 UTC by lxxjxxki

아직 초보라 docs, mvc 분리는 다음에 하겠습니다 ㅠ

2023-10-05 13:18 UTC, younghoondoodoom requested changes
안녕하세요 진기님! 리뷰어 두둠이라고 합니다. 잘 부탁드립니다!
작성해주신 코드 잘 봤습니다 ㅎㅎ 기본적인 java 문법을 잘 숙지하고 계신것 같네요!

다만 java는 객체 지향 언어입니다! 객체 지향이란 유지 보수성에 집중하는 패러다임이라고 생각합니다! 
어떤 객체를 만들때나 메소드를 만들때 내가 아닌 다른 개발자가 이 객체를 잘 이용할 수 있을지, 잘 변경할 수 있을지를 항상 염두해두고 코드를 짠다면 훨씬 객체지향적인 코드가 나온답니다! 

간단하게 코멘트랑 추가 요구사항 드렸어요! 천천히 생각해보고 적용해보시면 좋을 것 같아요💪

2023-10-05 13:18 UTC, younghoondoodoom commented on src/main/java/penaltykick/Application.java
> +    }
class를 다른 파일로 분리하는게 더 가독성이 좋을 것 같습니다!

2023-10-05 13:18 UTC, younghoondoodoom commented on src/main/java/penaltykick/Application.java
> +    }
위 코멘트와 같은 생각입니다

2023-10-05 13:18 UTC, younghoondoodoom commented on src/main/java/penaltykick/Application.java
> +        }
객체를 생성할때 input을 넣어도 될거같아요!

2023-10-05 13:18 UTC, younghoondoodoom commented on src/main/java/penaltykick/Application.java
> +    private static char[] Result(Computer com, Player player) {
java에서는 메소드명을 camel case로 작성한답니다

2023-10-05 13:18 UTC, younghoondoodoom commented on src/main/java/penaltykick/Application.java
> +    private static final int zero = 0;
java에서는 상수를 snake case로 작성한답니다

2023-10-05 13:18 UTC, younghoondoodoom commented on src/main/java/penaltykick/Application.java
>      public static void main(String[] args) {
클래스 분리까지는 아니더라도 메소드 분리를 통해 해당 메소드를 사용하는 사용자에게 메세지를 던질 수 있어요! 메소드 분리를 하게되면 메소드명 + 파라미터 등으로 메세지를 던져줄 수 있답니다! 한번 한 메소드가 20줄이 넘지 않게 리펙토링 해보시겠어요?

2023-10-05 13:18 UTC, younghoondoodoom commented on src/main/java/penaltykick/Application.java
> +    private static void GameResult(Player player1, Player player2, Computer com) {
이 메소드에도 중복되는 부분이 보이네요! 한 메소드 당 20줄이 넘지 않게 리펙토링을 해보세요!
리펙토링을 진행할때 팁을 드리자면 이 메소드 or 객체를 사용하는 사람이 잘 알아보고 사용할 수 있을까?라는 생각을 자꾸하시면서 진행해보세요!

2023-10-06 18:41 UTC, lxxjxxki commented on src/main/java/penaltykick/Application.java
> +    private static void GameResult(Player player1, Player player2, Computer com) {
남겨주신 코멘트 전부 잘 봤습니다! 다음단계에서 좀 더 발전된 코드로 찾아뵙겠습니다
그 때 다시 찾아와주시면 감사드리겠습니다!

2023-10-07 08:14 UTC, merged